apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: Terraform
  patch: |-
    - op: add
      path: /spec/interval
      value: 5m
    - op: add
      path: /spec/approvePlan
      value: auto
resources:
- eu-west-1/
- us-east-1/
