apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: ConfigMap
  patch: |-
    - op: replace
      path: /data/eks_node_count
      value: 20
resources:
- account-01/
- account-02/
