apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-dev-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./terraform/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
