apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
replacements:
- path: ../../_transforms/name-from-repo.yaml
patchesJson6902:
- path: source.yaml
  target:
    kind: GitRepository
    name: stack
