apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./terraform/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
